# Generated by Django 5.1 on 2025-05-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_userreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
