# Generated by Django 5.1 on 2025-05-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_userreviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
